services:
    app:
        build: .
        container_name: SecretVaultManager
        restart: unless-stopped  # Riavvia automaticamente se crasha
        env_file: .env
        ports:
            - "3000:3000"
        networks:
            - secret_network

volumes:
    secret_data:

networks:
    secret_network:
        # internal: true # Isola la rete docker ~ non è accessibile dall'esterno
